---
- name: Slaves Config Playbook 
  hosts: slaves 
  become: true 
  tasks:
    - name: Copy installation script to remote host
      copy:
       src: /home/ubuntu/k8s/slave_installation.sh
       dest: /tmp/installation_script.sh
       mode: '0755'

    - name: Execute the installation script
      command: /tmp/installation_script.sh

    - name: Run additional command
      command: {copy the join command from command output file which generated after master playbook execution }
  
